### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by HuynhCynthia** [HuynhCynthia/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view 3 sections.
 1. Image of source code
 2. Code visualizer image
 3. Task list 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/115051720/232628012-4e3a102b-1ab5-411c-b5cf-06ae1f2907dc.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create component that will display name of example exercise file
- [ ] Create a component to display image of source code
- [ ] Create a component that will indicate what step of source code user is pointing to
- [ ] Create a component to display "code-visual" section
- [ ] Create a component to display task list section
- [ ] Create a component that will allow user to click on previous and next button

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
